apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: model-router-ingress
  namespace: default
spec:
  rules:
  - host: krakend.127.0.0.1.sslip.io
    http:
      paths:
      - backend:
          service:
            name: model-router-krakend
            port:
              number: 10000
        path: /
        pathType: Prefix