apiVersion: v1
kind: Service
metadata:
  name: model-router-krakend
  labels:
    app: model-router-krakend
  namespace: default
spec:
  selector:
    app: model-router-krakend
  ports:
    - protocol: TCP
      port: 10000
      targetPort: http
  type: ClusterIP